apiVersion: v1
kind: Pod
metadata:
  name: memory-demo-2
  namespace: mem-example
spec:
  containers:
  - image: polinux/stress
    name: memory-demo-2-ctr
    resources:
      limits:
        memory: 100Mi
      requests:
        memory: 50Mi
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "4G", "--vm-hang", "1"]
