apiVersion: v1
kind: ReplicationController
metadata:
    name: myapp-rc
    labels:
        app: myapp
        type: front-end
spec:
    template:
        metadata:
            name: myapp
            labels:
                app: myapp
                type: frontend
        spec:
            containers:
            - name: nging-container
              image: nginx
    replicas: 3
