# Create /tmp/users/user-details.csv file with $PASSWORD,$USERNAME,$USERID,"$LIST,$OF,$GROUPS" structure

# Modify the kube-apiserver startup options in kube-apiserver static pod on master under /etc/kubernetes/manifests/kube-apiserver.yaml with `- --basic-auth-files=/tmp/users/user-details.csv`

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
# This role binding allows "jane" to read pods in the "default" namespace.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
  namespace: default
subjects:
- kind: User
  name: user1 # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: pod-reader # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io


# Once created, you may authenticate into the kube-api server using the users credentials

# curl -v -k https://localhost:6443/api/v1/pods -u "user1:password123"
